// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqvrkfwzjyjfiinniciv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxdnJrZnd6anlqZmlpbm5pY2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDYxODEsImV4cCI6MjA3MzY4MjE4MX0.PH9vRZqfaQFppB8Q7UrFJwxNwIjp5CspbVZENraFe6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});